// Automatically generated by astro-icon
// dfdaebfb5010cf20b3694ad3522493b9a7d7d3427676a20d3f3e52b7bef4a88c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "argo"
		| "bolt"
		| "darkmode"
		| "datadog"
		| "email"
		| "fork"
		| "github"
		| "italy"
		| "lightmode"
		| "linkedin"
		| "medium"
		| "menu"
		| "neovim"
		| "paper"
		| "repo"
		| "rust";
}